stages:
  - build

include:

#   Mini PC board based on RK3568J SoC
  - local: .gitlab-ci/atb_rk3568j_mpc_linux-5.10.110.yml

#   Mini PC board with extensions based on RK3568J SoC
  - local: .gitlab-ci/atb_rk3568_mpc_m0_linux-5.10.110.yml

#   Mini PC board with extensions based on RK3568J SoC
  - local: .gitlab-ci/atb_rk3568_mpc_m1_linux-5.10.110.yml
  - local: .gitlab-ci/atb_rk3568_mpc_m1_linux-5.10.160.yml
  - local: .gitlab-ci/atb_rk3568_mpc_m1_linux-6.1.yml

#   SMARCv2.1 module of revision 0 based on RK3568J SoC
  - local: .gitlab-ci/atb_rk3568j_smc_linux-5.10.110.yml
  - local: .gitlab-ci/atb_rk3568j_smc_linux-5.10.110_uefi.yml

#   SMARCv2.1 module of revision 1 based on RK3568J SoC
  - local: .gitlab-ci/atb_rk3568j_smc_r1_linux-5.10.110.yml
  - local: .gitlab-ci/atb_rk3568j_smc_r1_linux-5.10.110_uefi.yml

#   Mini PC board based on RK3588 SoC
  - local: .gitlab-ci/atb_rk3588_mpc_linux-5.10.160.yml

#   Mini ATX board based on RK3588 SoC
  - local: .gitlab-ci/atb_rk3588_matx_linux-5.10.160.yml

#   SMARCv2.1 module of revision 0 based on RK3588 SoC
  - local: .gitlab-ci/atb_rk3588_smc_linux-5.10.160.yml
