atb_rk3588_smc_linux_5_10_160_build:
  stage: build
  tags: [buildroot]
  image: ubuntu:22.04
  timeout: 24h
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt install -y make cmake git gcc g++ mtools genext2fs cpio rsync bc file
    - apt install -y python2 python3 unzip wget bzip2 curlftpfs dosfstools
  script:
    - mkdir -p dl
    - curlftpfs -o user="atbftp_user:32Vj_hy%c@gR" ftp.atb-e.ru:2121/ATB_FTP/buildroot/dl dl
    - rm -rf output
    - make atb_rk3588_smc_linux-5.10.160_defconfig
    - make
  cache:
    key: atb_rk3588_smc_linux_5_10_160
    paths:
    - output/images
    - output/target
  rules:
    - if: $CI_PROJECT_NAME == "atb-buildroot-main"
      when: always
    - if: $CI_PROJECT_NAME != "atb-buildroot-main"
      when: manual

atb_rk3588_smc_linux_5_10_160_artifact:
  stage: artifact
  tags: [buildroot]
  needs: ["atb_rk3588_smc_linux_5_10_160_build"]
  script:
    - ls output/images
    - ls output/target
  cache:
    key: atb_rk3588_smc_linux_5_10_160
    paths:
    - output/images
    - output/target
  artifacts:
    name: atb_rk3588_smc_linux_5_10_160
    paths:
      - output/target
      - output/images/idblock.bin
      - output/images/uboot.img
      - output/images/Image
      - output/images/atb-rk3588-smc.dtb
      - output/images/rootfs.cpio.gz
  rules:
    - if: $CI_PROJECT_NAME == "atb-buildroot-main"
      when: always
    - if: $CI_PROJECT_NAME != "atb-buildroot-main"
      when: manual
