atb_rk3568j_mpc_linux-5.10.110:
  stage: build
  tags: [buildroot]
  image: ubuntu:22.04
  timeout: 24h
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt install -y make cmake git gcc g++ mtools genext2fs cpio rsync bc file
    - apt install -y python2 python3 unzip wget bzip2 curlftpfs dosfstools
  script:
    - mkdir -p dl
    - curlftpfs -o user="atbftp_user:32Vj_hy%c@gR" ftp.atb-e.ru:2121/ATB_FTP/buildroot/dl dl
    - make atb_rk3568j_mpc_linux-5.10.110_defconfig
    - make
  artifacts:
    name: "atb_rk3568j_mpc_linux-5.10.110"
    paths:
      - output/target
      - output/images/idblock.bin
      - output/images/uboot.img
      - output/images/Image
      - output/images/atb-rk3568j-mpc.dtb
      - output/images/rootfs.cpio.gz
  rules:
    - changes:
      - .gitlab-ci/atb_rk3568j_mpc_linux-5.10.110.yml
      - configs/atb_rk3568j_mpc_linux-5.10.110_defconfig
      - board/atb/atb_rk3568j_mpc/linux-5.10.110/*
      - board/atb/atb_rk3568j_mpc/uboot/*
      - board/atb/atb_rk3568j_mpc/overlay/*
      - board/atb/common/rk3568-post-image.sh
