atb_rk3568_mpc_m1_linux_6_1_build:
  stage: build
  tags: [buildroot]
  image: ubuntu:22.04
  timeout: 24h
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt update
    - apt install -y make cmake git gcc g++ mtools genext2fs cpio rsync bc file
    - apt install -y python2 python3 unzip wget bzip2 dosfstools
  script:
    - ln -s /buildroot/dl dl
    - make atb_rk3568_mpc_m1_linux-6.1_defconfig
    - make source
    - make
    - rm -f /buildroot/artifacts/$CI_PIPELINE_ID/atb_rk3568_mpc_m1_linux_6_1.tar.gz
    - tar -czf /buildroot/artifacts/$CI_PIPELINE_ID/atb_rk3568_mpc_m1_linux_6_1.tar.gz output/target output/images
  rules:
    - if: $CI_PROJECT_NAME == "atb-buildroot-main"
      when: always
    - if: $CI_PROJECT_NAME != "atb-buildroot-main"
      when: manual

atb_rk3568_mpc_m1_linux_6_1_upload_artifact:
  stage: upload_artifact
  tags: [buildroot]
  needs: ["atb_rk3568_mpc_m1_linux_6_1_build"]
  script:
    - tar -xf /buildroot/artifacts/$CI_PIPELINE_ID/atb_rk3568_mpc_m1_linux_6_1.tar.gz
  artifacts:
    name: "atb_rk3568_mpc_m1_linux_6_1"
    paths:
      - output/target
      - output/images/idblock.bin
      - output/images/uboot.img
      - output/images/Image
      - output/images/atb-rk3568-mpc-m1.dtb
      - output/images/rootfs.cpio.gz
  rules:
    - if: $CI_PROJECT_NAME == "atb-buildroot-main"
      when: always
    - if: $CI_PROJECT_NAME != "atb-buildroot-main"
      when: manual

atb_rk3568_mpc_m1_linux_6_1_clean:
  stage: clean
  tags: [buildroot]
  needs: ["atb_rk3568_mpc_m1_linux_6_1_upload_artifact"]
  script:
    - rm -f /buildroot/artifacts/$CI_PIPELINE_ID/atb_rk3568_mpc_m1_linux_6_1.tar.gz
  rules:
    - if: $CI_PROJECT_NAME == "atb-buildroot-main"
      when: always
    - if: $CI_PROJECT_NAME != "atb-buildroot-main"
      when: manual
